### ISSUE TITLE
Snap package for reicast

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1138]
I've configured http://build.snapcraft.io to automatically build master and publish to the edge channel.  

`snap install reicast --edge` will get the latest master build. We should document this somewhere so that users can find it. Once things are more stable we can make a 'stable' release that will appear in the ubuntu store

TODOs:
- [ ] Update README.md on how to use the snap package, `snap install reicast --edge`, and snap home directories
- [ ] Fix armhf and arm64 builds _(armhf: assembly error from neon missing, arm64: failed to detect arch)_
- [ ] Our snap size is 80 MiB. Can it be reduced? 
- [ ] Make Reicast more snap friendly. See https://docs.snapcraft.io/reference/env
- [ ] Investigate status integration in GH for pull requests
- [ ] Investigate auto releases via tags?

*edit*
[![Snap Status](https://build.snapcraft.io/badge/reicast/reicast-emulator.svg)](https://build.snapcraft.io/user/reicast/reicast-emulator) should work as a general indicator

**Comment by rrrh** [comment]
The "arm64: failed to detect arch" part is interesting to me. Will have a look what else I can do for the other action points.

**Comment by natehaxx** [comment]
well i am running an Tegra X1 inside my nintendo switch with aarch64 , and right now the snap build fails any guess ?

**Comment by rrrh** [comment]
Do you have any more information on the "and right now the snap build fails" part.

**Comment by skmp** [comment]
Made aarch64 default to lincpp, so at least it compiles, even if perf suffers

**Comment by luserx0** [comment]
Have we actually released a stable version of snap? Do you remember @skmp?
I find the goals about size reducal and integration with GH PRs unnecessary (too-much-of-a-hassle-I-would-say)
Why? Because the goddamn thing is slow and it breaks easily (i.e misplacing reicast.png breaks the whole build). Reducing size would have to tailor the build further and using it with our GH doesn' make sense since an amd64 linux build could take up to half an hour

**Comment by luserx0** [comment]
_I'll update to the initial points of the issue referencing numerically:_

1. Done, we currently don't support that many things, but I trust that I've "spammed" it enough
2. Testing a neon fix. -- Help needed 
3. You can use **unsquashfs -l** on the resulting .snap file of a local build to check which files are included; then the **prime** keyword of snap can help choose which files should be included -- Not familiar with what should and what should not
4. WIP
5. Circle Ci and LaunchPad could support status integration in PRs. Travis CI looks tracks single branches only
6. Achievable with Travis -- Need an ubuntu machine to replicate

Additional Notes:
- We could add channels for all our releases and supply more channel options
- Testing should take place to a docker container for the benefits of clean environment to be sure end users won't complain about (any?) missing packages
- Researching on cmake integration (Link)[https://github.com/ubuntu/snappy-playpen/search?utf8=%E2%9C%93&q=%22plugin%3A+cmake%22&type=Code]
- Light research on gradle possibilities
