### ISSUE TITLE
Work tracking: Core scripting & TAS features

### ISSUE THREAD

**Issue by gigaherz** [reicast/reicast-emulator#1659]
This is a task ticket for tracking my sponsored work.

See #1031 for TAS feature request.

Goals, in the order I come up with them:
- [ ] Add LUA runtime and look into bindings
- [ ] Decide what features should be exposed to lua (comments welcome, specially from anyone who is interested in game modding and TAS)
- [ ] Implement LUA bindings as needed
- [ ] Implement frame-stepping
- [ ] Implement input dumping and replay engine
- [ ] Implement some kind of manual input display/selection (could leverage the touch input UI?)
- [ ] Tie the replay engine into the savestate system, so replays/recording can be restarted from a savestate

**Comment by skmp** [comment]
Any progress on this giga?

**Comment by gigaherz** [comment]
Reicast is currently able to load a script from a hardcoded path, and I'm in the middle of writing a library of basic bindings that I could come up with. I suppose that would be the first step done...

**Comment by skmp** [comment]
Have it up on a branch yet?

**Comment by gigaherz** [comment]
Nah since I didn't tie it into the main build system I thought I'd wait, but I can push... *pushes*

**Comment by skmp** [comment]
@gigaherz any updates? :P

**Comment by gigaherz** [comment]
Updated TODO list

**Comment by skmp** [comment]
@gigaherz any updates on this?
