### ISSUE TITLE
Summertime Refactor

### ISSUE THREAD

**Issue by skmp** [reicast/reicast-emulator#1664]
Over the summer I hope to completely revamp the source code, in incremental steps.

Please try to open your PRs as soon as plausible, and to keep them around for as little as possible. I’ll do my best to do in small steps, with quick merges, and i’ll make sure to transition new code as it gets written.

I propose to make a new branch “development” and to only merge to master as things are stable. Master pushes push downstream to users and other projects, and we don’t want to keep breaking things every second day for them.

Summer refactor next steps
---
Aiming for a clean and nice codebase
- [x] GLES & jit init (#1660)
- [x] page fault marshaling for linux (#1683)
- [x] Investigate Android TV listing issue
- [x] Split UI to many files
- [ ] Support multiple glinits
- [ ] Refactor the speed limit logic
- [ ] Dependecy-based builds
- [ ] Refactor UI more
- [ ] uninaoimi
- [ ] refactor and document the BM interface
- [ ] Overall structural documentation
- [ ] Unify naomi/aw/dc/etc builds
- [ ] vmem, cleanups
- [x] Full init refactor, oop style
- [ ] Add tests
- [ ] Offline compiler tools
- [ ] “fifoci”
- [ ] automated tests
- [ ] clean, per module savestates
- [ ] New build system, cleaned up build defs and such
- [ ] New CI system

Autumn plans
---
Aiming for 50% perf increase in the JIT side.
- [ ] Full SSA-based jit
- [ ] Unified mmu support
- [ ] multi block, constification, TCB GC
- [ ] New register allocator
- [ ] Unified jit backend for arm7, DSP and SH4

**Comment by skmp** [comment]
Related tickets: #473 #1141

**Comment by skmp** [comment]
Investigate (from #1651)

```07-01 12:41:16.372 I/reicast (17182): Verify Failed  : uStatus == GL_FRAMEBUFFER_COMPLETE
07-01 12:41:16.372 I/reicast (17182):  in init_output_framebuffer -> /home/travis/build/reicast/reicast-emulator/shell/android-studio/reicast/src/main/jni/../../../../../../core/rend/gles/gltex.cpp : 1062 
07-01 12:41:16.372 I/reicast (17182)

**Comment by skmp** [comment]
Making good progress at this, refactored large parts of `glwrap` and `glinit`, fixed several issues around our segfault handling, added cloudroms and some other minor stuff

See PRs #1693, #1694, #1697, #1696, #1702, #1703, #1704, #1705, #1706, #1710, #1711 and #1713
